name: Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: |
          npm run lint
          echo "Linting complete"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: |
          npm run test
          echo "Tests complete"
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: 
          echo "Deploying ..."

